### ISSUE TITLE
AMD and bower

### ISSUE THREAD

**Issue by marcinkr89** [DoclerLabs/Protip#29]
Hey,

when installing protip through bower only the minified and bundled versions of the script are downloaded. However, when requiring either of them via AMD they also try to require Item.js, Class.js etc. Is there any reason to it? Why the minified, production-ready script still needs other dependencies? 

The only solutions that come to mind are either adding sources to bower configuration or removing dependencies altogether from the minified version - could that be implemented?

**Comment by wintercounter** [comment]
The short answer: It doesn't, since dependencies are bundled inside the minified version. Those require/define statements should be resolved under the hood. The minfied versions are for browser usage and nothing else. In case you have to `require` on your own (because you're using Webpack, Babel, your own Browserify, etc., than skip bower and use the npm package itself:

```
// Install command:
npm install protip
// In `main.js` file:
require('protip');
```

**Comment by marcinkr89** [comment]
Thanks for a quick response.

Sadly, we can't use npm here, our development flow requires downloading scripts using bower (we use System.js, not webpack/browserify) and at the same time our framework loads JS modules on-demand. Whether that's the best solution is an entire different case :)

Right now I'll just justy manually copy necessary files as a temporary solution, but if you could add those sources to bower it would be great.

**Comment by wintercounter** [comment]
Done :) There is a main.js file, you just have to require that.

**Comment by marcinkr89** [comment]
Thanks!
